name: 03 - GCP - Build and Deploy Backend to GKE

# This workflow builds, tests, and deploys the backend Docker image to Google Kubernetes Engine using industry best practices.

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: us-central1 # Change as needed
      CLUSTER_NAME: rupaya-cluster
      SERVICE_NAME: rupaya-backend
      NAMESPACE: default
      IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/rupaya-backend:${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Authenticate to Google Cloud (OIDC)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --region $REGION

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Update deployment image
        run: |
          kubectl set image deployment/$SERVICE_NAME $SERVICE_NAME=$IMAGE -n $NAMESPACE
          kubectl rollout status deployment/$SERVICE_NAME -n $NAMESPACE

      - name: Notify
        run: echo "Deployed to GKE: deployment/$SERVICE_NAME"

      - name: Notify on failure
        if: failure()
        run: |
          echo "GKE deployment failed. Please check the logs."
