export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  INSUFFICIENT_FUNDS: 'ERR_INSUFFICIENT_FUNDS',
  UNKNOWN_ERROR: 'ERR_UNKNOWN_ERROR',
};