source "https://rubygems.org"

gem "fastlane", "~> 2.220"
gem "cocoapods", "~> 1.15"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'plugins')
eval(File.read(File.join(plugins_path, 'Gemfile'))) if File.exist?(pluginspath)
