source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '16.0'
use_frameworks!

target 'RUPAYA' do
  # Networking
  pod 'Alamofire', '~> 5.8'
  
  # Security
  pod 'KeychainAccess', '~> 4.2'
  
  # Analytics (optional)
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
